// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	gin "GoApiGin/src/api/vendor/github.com/gin-gonic/gin"

	mock "github.com/stretchr/testify/mock"
)

// IHealthStatus is an autogenerated mock type for the IHealthStatus type
type IHealthStatus struct {
	mock.Mock
}

// Ping provides a mock function with given fields: c
func (_m *IHealthStatus) Ping(c *gin.Context) {
	_m.Called(c)
}
